
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd note
      - run: ./install_dependency.sh
      - run: ./build.sh
