
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./note/cpp/install_dependency.sh
      - run: ./note/cpp/build.sh
