name: install dependencies and build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        shell: bash
        run: ./script/install_dependency.sh

      - name: build
        shell: bash
        run: ./script/build.sh
