name: install dependencies and build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        shell: bash
        run: ./scripts/install-dependencies.sh

      - name: build
        shell: bash
        run: ./scripts/build.sh
